name: Form Submission

on:
  push:
    branches:
      - main

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Send email
        run: |
          echo "Subject: New Form Submission" > email.txt
          echo "Name: ${{ secrets.NAME }}" >> email.txt
          echo "Email: ${{ secrets.EMAIL }}" >> email.txt
          echo "Message: ${{ secrets.MESSAGE }}" >> email.txt
          echo "PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}" >> email.txt
          cat email.txt | ssmtp teegalasreekar@gmail.com
        env:
          NAME: ${{ secrets.NAME }}
          EMAIL: ${{ secrets.EMAIL }}
          PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}
          MESSAGE: ${{ secrets.MESSAGE }}
        secrets:
          NAME: ${{ github.event.inputs.NAME }}
          EMAIL: ${{ github.event.inputs.EMAIL }}
          PHONE_NUMBER: ${{ github.event.inputs.PHONE_NUMBER }}
          MESSAGE: ${{ github.event.inputs.MESSAGE }}
